Models/Character Data/Alignment.cs
namespace Simple_DnD_Builder.Models.Character_Data
{
    public class Alignment
    {
       public readonly static string[] Alignments = new string[] {
           "chaotic-neutral",
            "chaotic-evil",
            "chaotic-good",
            "lawful-neutral",
            "lawful-evil",
            "lawful-good",
            "neutral",
            "neutral-evil",
            "neutral-good"};
        public Alignment(string index, string name, string abbr, string desc, string url)
        {
            Index = index;
            Name = name;
            Abbr = abbr;
            Desc = desc;
            Url = url;
        }
        public string Name { get; set; }
        public string Abbr { get; set; }
        public string Desc { get; set; }
        public string Url { get; set; }
        public string Index { get; set; }
    }
}

Controllers/AlignmentController.cs
using Microsoft.AspNetCore.Mvc;
using Simple_DnD_Builder.Models.Players;
using Simple_DnD_Builder.Repositories.Interfaces;

namespace Simple_DnD_Builder.Controllers
{
    public class AlignmentController : Controller
    {
        private readonly IAlignmentRepository _repo;
        public AlignmentController(IAlignmentRepository repo)
        {
            _repo = repo;
        }
        public IActionResult Index()
        {
            var alignments = _repo.GetAllAlignments();
            return View(alignments);
        }

        [HttpPost]
        public IActionResult AddAlignment(string selectedAlignment)
        {
            Player.Players[0].Alignment = selectedAlignment;
            return RedirectToAction("ViewPlayer", "Player", Player.Players[0]);
        }
        public IActionResult ViewAlignment(string index)
        {
            var Alignment = _repo.GetAlignmentByIndex(index.ToLower());
            return View(Alignment);
        }
    }
}

Views/Alignment/Index.cshtml
@using Simple_DnD_Builder.Models.Character_Data;
@model List<Alignment>

<h2>Choose a Alignment</h2>
<p>Click Alignment for more information</p>
@using (Html.BeginForm("AddAlignment", "Alignment", FormMethod.Post))
{
    <table class="table">
        <tr>
            <th>Select Alignmenmt</th>
            <th>Name</th>
            <th>abbr</th>
            <th>Desciption</th>
            
        </tr>

        @foreach (var Alignment in Model)
        {
            <tr>
                <td><input type="radio" name="selectedAlignment" value="@Alignment.Name"></td>
                <td><a href="/Alignment/ViewAlignment?index=@Alignment.Index">@Alignment.Name</a></td>
                <td>@Alignment.Abbr</td>
                <td>@Alignment.Desc</td>             
                
            </tr>
        }
    </table>
    <button type="submit">Add Selected Alignment</button>
}

Views/Alignment/ViewAlignment.cshtml
@using Simple_DnD_Builder.Models.Character_Data;
@model Alignment

<h2>@Model.Name</h2>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Abbreviation</th>
        <th>Description</th>
        <th>URl</th>
        

    </tr>


    <tr>
        <td>@Model.Name</td>
        <td>@Model.Abbr </td>
        <td>@Model.Desc</td>
        <td>@Model.Url</td>
       

    </tr>
    @Html.ActionLink("Go Back", "Index", "Alignment", null, new { @class = "btn btn-primary" })

</table>