Models/Races/Race.cs
namespace Simple_DnD_Builder.Models.Races
{
    public class Race
    {
        public static readonly string[] Races = new string[]
            
            {
                "dragonborn",
                "dwarf",
                "elf",
                "gnome",
                "half-elf",
                "half-orc",
                "halfling",
                "human",
                "tiefling"
            };
    public Race(string name, int speed, string alignment, string age, string size, string sizeDecription, string languageDescription, string url)
        {
            Name = name;
            Speed = speed;
            Alignment = alignment;
            Age = age;
            Size = size;
            SizeDescription = sizeDecription;
            LanguageDescription = languageDescription;
            Url = url;
        }
     
    
        public string Name { get; set; }
        public int Speed { get; set; }
        public string Alignment { get; set; }
        public string Age { get; set; }
        public string Size { get; set; }
        public string SizeDescription { get; set; }
        public string LanguageDescription { get; set; }
        public string Url { get; set; }

    }
}

Controllers/RaceController.cs
using Microsoft.AspNetCore.Mvc;
using Simple_DnD_Builder.Models.Players;
using Simple_DnD_Builder.Models.Races;
using Simple_DnD_Builder.Repositories.Interfaces;
using System.Numerics;

namespace Simple_DnD_Builder.Controllers
{
    public class RaceController : Controller
    {
       private readonly IRaceRepository _repo;

        public RaceController(IRaceRepository repo)
        {
            _repo = repo;
        }
        public IActionResult Index()
        {
            var races = _repo.GetAllRaces();
            return View(races);
        }
        [HttpPost]
        public IActionResult AddRace(string selectedRace)
        {
            if (Player.Players[0].Race != null) _repo.DecreasePlayerAbilityScore(Player.Players[0]);
            _repo.IncreasePlayerAbilityScore(Player.Players[0], selectedRace);        
            Player.Players[0].Race = selectedRace;
            return RedirectToAction("ViewPlayer", "Player", Player.Players[0]);
        }
        public IActionResult ViewRace(string index)
        {
            var race = _repo.GetRaceByIndex(index.ToLower());
            return View(race);
        }
    }
}

Views/Race/Index.cshtml
@using Simple_DnD_Builder.Models.Races;
@model List<Race>

<h2>Choose a Race</h2>
<p>Click race name for more information</p>
@using (Html.BeginForm("AddRace", "Race", FormMethod.Post))
{
    <table class="table">
        <tr>
            <th>Choose a Race</th>
            <th>Name</th>
            <th>Speed</th>
            <th>Alignment</th>
            <th>Age</th>
            <th>Size</th>
        </tr>

        @foreach (var race in Model)
        {
            <tr>
                <td><input type="radio" name="selectedRace" value="@race.Name.ToLower()"></td>
                <td><a href="/Race/ViewRace?index=@race.Name">@race.Name</a></td>
                <td>@race.Speed</td>
                <td>@race.Alignment</td>
                <td>@race.Age</td>
                <td>@race.Size</td>
               
            </tr>
        }
    </table>
    <button type="submit">Add Selected Race</button>
}

Views/Race/ViewRace.cshtml
@using Simple_DnD_Builder.Models.Races;
@model Race

<h2>@Model.Name</h2>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Size</th>
        <th>Speed</th>
        <th>Alignment</th>
        <th>Size</th>
        <th>Size Description</th>
        <th>Language Description</th>

    </tr>


    <tr>
        <td>@Model.Name</td>
        <td>@Model.Size </td>
        <td>@Model.Speed</td>
        <td>@Model.Alignment</td>
        <td>@Model.Size</td>
        <td>@Model.SizeDescription</td>
        <td>@Model.LanguageDescription</td>

    </tr>
    @Html.ActionLink("Go Back", "Index", "Race", null, new { @class = "btn btn-primary" })

</table>