Models/CharClass/CharClass.cs
namespace Simple_DnD_Builder.Models.CharClass
{
    public class CharClass
    {
        public static readonly string[] Classs = new string[] {
                "barbarian",
                "bard",
                "cleric",
                "druid",
                "fighter",
                "monk",
                "paladin",
                "ranger",
                "rogue",
                "sorcerer",
                "warlock",
                "wizard"};
        public CharClass(string name, int hitDice, List<string> savingthrows) 
        {
            Name = name;
            HitDice = hitDice;
            SavingThrows = savingthrows.ToArray();
        }
        public int Level { get; set; }
        public string Name { get; set; }
        public int HitDice { get; set; }
        public string[] SavingThrows { get; set; }

    }
}

Controllers/CharClassController.cs
using Microsoft.AspNetCore.Mvc;
using Simple_DnD_Builder.Models.Players;
using Simple_DnD_Builder.Repositories.Interfaces;

namespace Simple_DnD_Builder.Controllers
{
    public class CharClassController : Controller
    {
        private readonly ICharClassRepository _repo;
        public CharClassController(ICharClassRepository repo)
        {
            _repo = repo;
        }
        public IActionResult Index()
        {
            var classes = _repo.GetAllCharClass();
            return View(classes);
        }
       
        [HttpPost]
        public IActionResult AddCharClass(string selectedCharClass)
        {
            Player.Players[0].CharClass = selectedCharClass;
            return RedirectToAction("ViewPlayer", "Player", Player.Players[0]);
        }
        public IActionResult ViewCharClass(string index)
        {
            var charClass = _repo.GetCharClassByIndex(index.ToLower());
            return View(charClass);
        }
    }
}

Views/CharClass/Index.cshtml
@using Simple_DnD_Builder.Models.CharClass;
@model List<CharClass>

<h2>Choose a Class</h2>
<p>Click Class for More Information</p>
@using (Html.BeginForm("AddCharClass", "CharClass", FormMethod.Post))
{
    <table class="table">
        <tr>
            <th>Select Class</th>
            <th>Name</th>
            <th>Hit Dice</th>
            
        </tr>

        @foreach (var CharClass in Model)
        {
            <tr>
                <td><input type="radio" name="selectedCharClass" value="@CharClass.Name"></td>
                <td><a href="/CharClass/ViewCharClass?index=@CharClass.Name">@CharClass.Name</a></td>
                <td>@CharClass.HitDice</td>
            </tr>
        }
    </table>
    <button type="submit">Add Selected Class</button>
}

Views/CharClass/ViewCharClass.cshtml
@using Simple_DnD_Builder.Models.CharClass;
@model CharClass

<h2>@Model.Name</h2>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Hit Dice</th>
    </tr>
    <tr>
        <td>@Model.Name</td>
        <td>@Model.HitDice </td>  
    </tr>
</table>
<h2>Saving Throws</h2>
@foreach (var abil in Model.SavingThrows)
{
    <td><a href="/AbilityScore/ViewAbilityScore?index=@abil">@abil.ToUpper()</a></td>
}
@Html.ActionLink("Go Back", "Index", "CharClass", null, new { @class = "btn btn-primary" })