Models/Character Data/Helpers/PlayerHelper.cs
namespace Simple_DnD_Builder.Models.Players
{
    public class PlayerHelper
    {
        public static void PlayerPurger() 
        {
        for(int i = Player.Players.Count - 1; i > 0; i--)
            {
                Player.Players.RemoveAt(i);
            }
        }
    }
}

Models/Player/Player.cs
using Simple_DnD_Builder.Models.Character_Data;
using Simple_DnD_Builder.Models.Class;
using Simple_DnD_Builder.Models.Races;

namespace Simple_DnD_Builder.Models.Player
{
    public class Player
    {
        public static List<Player> Players = new List<Player>();
        public Player()
        {
          
        }
        public string Name { get; set; }
        public string PlayerName { get; set; }
        public string Gender { get; set; }
        public Race Race { get; set; }
        public CharClass CharClass { get; set; }
        public Dictionary<string, int> AbilityScores { get; set; }
        public Alignment Alignment { get; set; }
        public List<Language> Languages { get; set; }
        public Dictionary<string, int> SkillScores { get; set; }
        public string ImageURL { get; set; }

        

    }
}

Models/Player/PlayerHelper.cs
namespace Simple_DnD_Builder.Models.Player
{
    public class PlayerHelper
    {
        public static void PlayerPurger() 
        {
        for(int i = Player.Players.Count - 1; i > 0; i--)
            {
                Player.Players.RemoveAt(i);
            }
        }
    }
}

Models/Players/Player.cs
using Simple_DnD_Builder.Models.Character_Data.Helpers;
using System.Numerics;

namespace Simple_DnD_Builder.Models.Players
{
    public class Player
    {
        public static List<Player> Players = new List<Player>();
        public Player()
        {
            this.AbilityScores= AbilityHelper.AbilityAdder();
            this.SkillScores = SkillHelper.SkillsAdder();
        }
        public enum stanardArray:int {eight = 8, ten = 10, twelve = 12, thirteen = 13, fourteen = 14 , fifteen = 15};
        public string Name { get; set; }
        public string PlayerName { get; set; }
        public string Gender { get; set; }
        public string Race { get; set; }
        public string CharClass { get; set; }
        public Dictionary<string, int> AbilityScores { get; set; } = new Dictionary<string, int>();
        public string Alignment { get; set; }
        public List<string> Languages { get; set; }
        public Dictionary<string, int> SkillScores { get; set; } = new Dictionary<string, int>();
        public string ImageURL { get; set; }

        

    }
}

Controllers/PlayerController.cs
using Microsoft.AspNetCore.Mvc;
using Simple_DnD_Builder.Models.Character_Data.Helpers;
using Simple_DnD_Builder.Models.Players;

namespace Simple_DnD_Builder.Controllers
{
    public class PlayerController
        : Controller
    {

        public IActionResult Index()
        {
            PlayerHelper.PlayerPurger();
            return (Player.Players.Count == 0) ? RedirectToAction("PlayerCreator") : RedirectToAction("PlayerChooser"); ;
        }
        public IActionResult ViewPlayer()
        {
            PlayerHelper.PlayerPurger();
            return View(Player.Players[0]);
        }
        public IActionResult PlayerChooser()
        {
            PlayerHelper.PlayerPurger();
            return View(Player.Players);
        }
        public IActionResult PlayerCreator()
        {
            PlayerHelper.PlayerPurger();
            return Player.Players.Count == 0? View(new Player()): View(Player.Players[0]);

        }
        public IActionResult CreatePlayer(Player player)
        {
            if (player.PlayerName == null || player.Name == null || player.Gender == null)
            {
                return RedirectToAction("PlayerCreator");
            }
            switch (player.Gender)
            {
                case "Male":
                    player.ImageURL = "https://lh6.googleusercontent.com/R58vQJ2Mh1Uf1QcsHi4Z9AbRI7Rhl4JBE4OwqNqX3ZWWWEj1dkVmxJzjzVr21S5JihueMFyzdDT2lDGAy3MuFBxZClVectkLtynH-E5v50hSOW9Sot1rqNaOaHDVtq_FPvaVx5W7";
                    break;
                case "Female":
                    player.ImageURL = "https://forgeofmyth.files.wordpress.com/2018/09/dnd_image_001.jpg";
                    break;
                default:
                    player.ImageURL = "https://pbs.twimg.com/media/Ec5pwCeXgAIEdcF.jpg";
                    break;
            }
            //AbilityHelper.AbilityAdder(player);
            //SkillHelper.SkillsAdder(player);
            Player.Players.Add(player);
            PlayerHelper.PlayerPurger();
            return RedirectToAction("ViewPlayer");

        }

    }
}

Views/Player/Index.cshtml
@using Simple_DnD_Builder.Models.Players;
@model Player

<h2>@Model.Name</h2>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Race</th>
        <th>Class</th>
        <th>Alignment</th>

    </tr>


    <tr>
        <td>@Model.Name</a></td>
        <td>@(@Model.Race.Length == 0) ? <a href=/Race/Index />Choose a Race</a> : @Model.Race</td>
        <td>@(@Model.CharClass.Length == 0) ? <a href=/CharClass/Index />Choose a Class</a> : @Model.CharClass</td>
        <td>@(@Model.Alignment.Length == 0) ? <a href=/Alignment/Index />Choose an Alignment</a> : @Model.Race</td>        
    </tr>


</table>

Views/Player/PlayerChooser.cshtml
@using Simple_DnD_Builder.Models.Players;
@model List<Player>

<h2>Choose Your Player</h2>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Player Name</th>
    </tr>

    @foreach (var player in @Model)
    {
        <tr>
            <td><a href=/player/viewplayer/@player.PlayerName>@player.PlayerName</a></td>
            <td>@player.Name</td>
           
        </tr>
    }

</table>

Views/Player/PlayerCreator.cshtml
@using Simple_DnD_Builder.Models.Players;
@model Player

<h3>
    @(Model.Name == null ?
        "Let's Get Started" :
        "Edit Your Character")
</h3>
@using (Html.BeginForm("CreatePlayer", "Player", "Post"))
{
    

    <label asp-for="PlayerName" class="control-label">Your Name</label>
    <input type="text" name="PlayerName" class="form-control"  />

    <label asp-for="Name" class="control-label">Your Character's Name</label>
    <input type="text"  name="Name" class="form-control" />

<label asp-for="Gender" class="control-label">Gender</label>
<div class="form-control">
    <input type="radio" id="genderfemale" name="Gender" value="Female">
    <label for="genderfemale">Female</label><br>
    <input type="radio" id="genderFNC" name="Gender" value="GenderFNC">
    <label for="genderFNC">Gender Fluid/Nonconforming</label><br>
    <input type="radio" id="gendermale" name="Gender" value="Male">
    <label for="gendermale">Male</label>
</div>
   
    <input type="submit" value="Create Character" class="btn btn-primary" />
}

Views/Player/ViewPlayer.cshtml
@using Simple_DnD_Builder.Models.Players;
@model Player
@{
    int counter = 0;
}
<h2>@Model.PlayerName 's Character @Model.Name</h2>
<img src="@Model.ImageURL" alt="Your Character" />
<table class="table">
    <tr>
        <th>Name</th>
        <th>Race</th>
        <th>Class</th>
        <th>Alignment</th>

    </tr>


    <tr>
        <td><a href='/Player/PlayerCreator'>@Model.Name</a></td>
        <td>
            @(Model.Race == null ?
            Html.Raw("<a href='/Race/Index'>Choose a Race</a>") :
            Html.Encode(Model.Race))
        </td>

        <td>
            @(Model.CharClass == null ?
            Html.Raw("<a href='/CharClass/Index'>Choose a Class</a>") :
            Html.Encode(Model.CharClass))
        </td>

        <td>
            @(Model.Alignment == null ?
            Html.Raw("<a href='/Alignment/Index'>Choose an Alignment</a>") :
            Html.Encode(Model.Alignment))
        </td>
    </tr>
</table>
    <h4>Abilty Scores</h4>
    <p>Click Ability for more information</p>
    <div class="row">
    <div class="col-md-1"><a href="/AbilityScore/ViewAbilityScore?index=cha"> CHA = @Model.AbilityScores["cha"]</a></div>
    <div class="col-md-1"><a href="/AbilityScore/ViewAbilityScore?index=con">CON = @Model.AbilityScores["con"]</a></div>
    <div class="col-md-1"><a href="/AbilityScore/ViewAbilityScore?index=dex">DEX = @Model.AbilityScores["dex"]</a></div>
    </div>
    <div class="row">
    <div class="col-md-1"><a href="/AbilityScore/ViewAbilityScore?index=int">INT = @Model.AbilityScores["int"]</a></div>
    <div class="col-md-1"><a href="/AbilityScore/ViewAbilityScore?index=str">STR = @Model.AbilityScores["str"]</a></div>
    <div class="col-md-1"><a href="/AbilityScore/ViewAbilityScore?index=wis">WIS = @Model.AbilityScores["wis"]</a></div>
    </div>
    <h4>Skill Scores</h4>
    <p>Click Skill for More information</p>
@for(int j = 0; j < 3; j++)
{
    <div class="row">
    @for (int i = 0; i < 6; i++)
    {
            <div class="col-md-1"><a href="/skill/index?index=@Skill.Skills[counter]">@Skill.Skills[@counter].Replace('-', ' ')</a> <br />------------<br /> @Model.SkillScores[@Skill.Skills[@counter++]]</div>
    }
    </div>
}

       
    @*
        <div class="col-md-1">@Skill.Skills[@counter].Replace('-', ' ') <br  />------------<br /> @Model.SkillScores[@Skill.Skills[@counter++]]</div>
        <div class="col-md-1">@Skill.Skills[@counter].Replace('-', ' ') <br  />------------<br /> @Model.SkillScores[@Skill.Skills[@counter++]]</div>
        <div class="col-md-1">@Skill.Skills[@counter].Replace('-', ' ') <br  />------------<br /> @Model.SkillScores[@Skill.Skills[@counter++]]</div>
        <div class="col-md-1">@Skill.Skills[@counter].Replace('-', ' ') <br  />------------<br /> @Model.SkillScores[@Skill.Skills[@counter++]]</div>
        <div class="col-md-1">@Skill.Skills[@counter].Replace('-', ' ') <br  />------------<br /> @Model.SkillScores[@Skill.Skills[@counter++]]</div>                
   
     <div class="row">
        <div class="col-md-1">@Skill.Skills[@counter].Replace('-', ' ') <br  />------------<br /> @Model.SkillScores[@Skill.Skills[@counter++]]</div>
        <div class="col-md-1">@Skill.Skills[@counter].Replace('-', ' ') <br  />------------<br /> @Model.SkillScores[@Skill.Skills[@counter++]]</div>
        <div class="col-md-1">@Skill.Skills[@counter].Replace('-', ' ') <br  />------------<br /> @Model.SkillScores[@Skill.Skills[@counter++]]</div>
        <div class="col-md-1">@Skill.Skills[@counter].Replace('-', ' ') <br  />------------<br /> @Model.SkillScores[@Skill.Skills[@counter++]]</div>
        <div class="col-md-1">@Skill.Skills[@counter].Replace('-', ' ') <br  />------------<br /> @Model.SkillScores[@Skill.Skills[@counter++]]</div>
        <div class="col-md-1">@Skill.Skills[@counter].Replace('-', ' ') <br  />------------<br /> @Model.SkillScores[@Skill.Skills[@counter++]]</div>                
    </div>
    <div class="row">
        <div class="col-md-1">@Skill.Skills[@counter].Replace('-', ' ') <br />------------<br /> @Model.SkillScores[@Skill.Skills[@counter++]]</div>
        <div class="col-md-1">@Skill.Skills[@counter].Replace('-', ' ') <br />------------<br /> @Model.SkillScores[@Skill.Skills[@counter++]]</div>
        <div class="col-md-1">@Skill.Skills[@counter].Replace('-', ' ') <br />------------<br /> @Model.SkillScores[@Skill.Skills[@counter++]]</div>
        <div class="col-md-1">@Skill.Skills[@counter].Replace('-', ' ') <br />------------<br /> @Model.SkillScores[@Skill.Skills[@counter++]]</div>
        <div class="col-md-1">@Skill.Skills[@counter].Replace('-', ' ') <br />------------<br /> @Model.SkillScores[@Skill.Skills[@counter++]]</div>
        <div class="col-md-1">@Skill.Skills[@counter].Replace('-', ' ') <br />------------<br /> @Model.SkillScores[@Skill.Skills[@counter++]]</div>
    </div>*@
    